kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ipFamily: dual
  kubeProxyMode: nftables
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30010
        hostPort: $HOST_HTTP_PORT
        protocol: TCP
      - containerPort: 30011
        hostPort: $HOST_HTTPS_PORT
        protocol: TCP
